GET http://localhost:5700/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTIxNzY3MTQsImV4cCI6MTYxMjE3Njc0NCwiYXVkIjoiNjAxNmIwZDY5YWI1Y2M0MDNjZWFjMzE4IiwiaXNzIjoiQXN0ZXIuY29tIn0.hg8XnbaNPyXqoQES1iSSIdVcZUXi1D2rgKHnlPYK3cg

###Error route
Get http://localhost:5700/abc

###register route
POST http://localhost:5700/user/register
Content-Type: application/json

{
    "email": "aster@gmail.com",
    "password": "aster"
}

###login route
POST http://localhost:5700/user/login
Content-Type: application/json

{
    "email": "alister@gmail.com",
    "password": "alister"
}

###refresh token route
POST http://localhost:5700/user/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTIzMzUzNDQsImV4cCI6MTY0Mzg5Mjk0NCwiYXVkIjoiNjAxNmIwZDY5YWI1Y2M0MDNjZWFjMzE4IiwiaXNzIjoiQXN0ZXIuY29tIn0.nu4XCJl30LAnpsBpyPAWNL0PdQ_BeytvGltFaeFZuFM"
}

###logout route
DELETE http://localhost:5700/user/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTIzMzUzOTEsImV4cCI6MTY0Mzg5Mjk5MSwiYXVkIjoiNjAxNmIwZDY5YWI1Y2M0MDNjZWFjMzE4IiwiaXNzIjoiQXN0ZXIuY29tIn0.bJ4TZtGhqJHbGWH41lYTQFH0CrlBPO11dyuUiyI7sVA"
}