GET http://localhost:5700/
Authorization: Bearer xx.yy.zz

###Error route
Get http://localhost:5700/abc

###register route
POST http://localhost:5700/user/register
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###login route
POST http://localhost:5700/user/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###refresh token route
POST http://localhost:5700/user/refresh-token
Content-Type: application/json

{
    "refreshToken": ""
}

###logout route
DELETE http://localhost:5700/user/logout
Content-Type: application/json

{
    "refreshToken": ""
}
